language: node_js
os: linux
dist: xenial
node_js:
  - lts/*
cache:
  npm: false
  yarn: true
notifications:
  email: false
git:
  quiet: true
install: 
  - "yarn install --frozen-lockfile"
  - "sh ./scripts/configure-git.sh"
before_script:
  - "yarn bootstrap"
script: 
  - "yarn lint"
  - "yarn test --runInBand"
  - "bash <(curl -s https://codecov.io/bash)"
jobs:
  tex:
    name: Installing TeX Live and ((Xe)La)TeX related packages
    runs-on: ubuntu-latest
    shell: bash
    steps:
      - name: Install sudo package
        run: apt update && apt install sudo
      - name: Installing TeX Live
        run: |
          sudo apt-get update
  include:
    - stage: check
      name: "Confidence check"
      if: type = push AND branch != master
    - stage: update-files
      name: "Update Files"
      if: type = push AND branch =~ /.*\(icons?\).*/
      before_script:
        - "yarn build:icons"
      script: "sh ./scripts/update-files.sh"
    - stage: release
      name: "Release"
      if: type = push AND branch = master
      before_deploy:
        - "yarn build"
        - "yarn test:regression:docker:update"
        - "npm config set '//registry.npmjs.org/:_authToken' '${NPM_AUTH_TOKEN}'"
        - "yarn config set _authToken '${NPM_AUTH_TOKEN}'"
        - "sh ./scripts/update-files.sh"
        - "yarn release:ci"
        - "sh ./packages/natds-icons/android/publish_lib.sh"
      deploy:
        - provider: script
          script: "yarn lerna:publish:ci"
          skip_cleanup: true
          on:
            branch: master
