name: Icon-regression
on: pull_request
jobs:
  regression:
    runs-on: ubuntu-latest
    name: Regression test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Regression Test
      run: yarn test:regression:docker
      continue-on-error: true
    - name: Create Comment
      id: create_comment
      env:
        IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
      run: |
        OUTPUT=$(bash ./scripts/build-regression-comment.sh)
        OUTPUT="${OUTPUT//'%'/'%25'}"
        OUTPUT="${OUTPUT//$'\n'/'%0A'}"
        OUTPUT="${OUTPUT//$'\r'/'%0D'}"
        echo "::set-output name=comment::$OUTPUT"
    - name: Post comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: regression_test
        message: |
          ${{ steps.create_comment.outputs.comment }}
on: pull_request_review_comment
jobs:
  update_regression:
    runs-on: ubuntu-latest
    name: Regression test
    steps:
    - name: Regression Test Update
      run: echo "foi"
