name: Icon-regression-Update
on:
  issue_comment:
    types: [created, edited]
jobs:
  update_regression:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '[update regression]')
    runs-on: ubuntu-latest
    name: Regression test
    steps:
    - name: Dump context
      uses: crazy-max/ghaction-dump-context@v1
    - name: Get the latest commit on PR
      id: get-latest-commit
      uses: ActionsRML/get-PR-latest-commit@master
      with:
        pull_number: ${{ github.event.issue.number }}
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.get-latest-commit.outputs.latest_commit_sha }}
    - name: Regression Test Update
      run: yarn test:regression:docker:update
    - uses: EndBug/add-and-commit@v5
      with:
        add: './packages/natds-icons/regression/__image_snapshots__'
        author_name: Design System via github action
        author_email: designsystem@natura.net
        message: 'chore: updating icons regression test reference image [skip ci]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
